const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { isValidGuestId, normalizeGuestId } = require('../server/services/clientIdentityService');

const apiSource = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'api.js'), 'utf8');
const bookmarkRouteSource = fs.readFileSync(path.join(__dirname, '..', 'server', 'routes', 'bookmarks.js'), 'utf8');

test('guest identity accepts every format generated by the web client', () => {
  assert.equal(isValidGuestId('guest_123456789'), true);
  assert.equal(isValidGuestId('guest_550e8400-e29b-41d4-a716-446655440000'), true);
  assert.equal(isValidGuestId('guest_lz123abc_qwerty987'), true);
  assert.equal(isValidGuestId('guest_bad space'), false);
  assert.equal(isValidGuestId('other_550e8400-e29b-41d4-a716-446655440000'), false);
});

test('guest identity remains bounded and normalized', () => {
  assert.equal(normalizeGuestId('  guest_123456789  '), 'guest_123456789');
  assert.equal(isValidGuestId(`guest_${'a'.repeat(81)}`), false);
  assert.equal(isValidGuestId('guest_short'), false);
});

test('bookmark identity boundary uses the shared validator', () => {
  assert.match(bookmarkRouteSource, /normalizeGuestId, isValidGuestId/);
  assert.match(bookmarkRouteSource, /isValidGuestId\(guestId\)/);
  assert.match(apiSource, /globalThis\.crypto\?\.randomUUID/);
  assert.match(apiSource, /guest_\$\{Date\.now\(\)\.toString\(36\)\}_/);
});
