const express = require('express');
const router = express.Router();
const db = require('../db');
const { requireAdmin } = require('../middleware/auth');

function rowToDeal(r) {
  if (!r) return null;
  let reviews = [];
  try { reviews = typeof r.reviews === 'string' ? JSON.parse(r.reviews) : (r.reviews || []); } catch {}
  const now = Math.floor(Date.now() / 1000), isExpired = r.is_expired === 1 || r.status === 'EXPIRED';
  const expiredAt = r.expired_at || null, purgeInSeconds = isExpired && expiredAt ? Math.max(0, 86400 - (now - expiredAt)) : null;
  return { id:r.id,title:r.title,asin:r.asin,category:r.category,originalPrice:Number(r.original_price ?? 0),salePrice:Number(r.sale_price ?? 0),discountPercent:Number(r.discount_percent ?? 0),imageUrl:r.image_url,productUrl:r.product_url,rating:Number(r.rating ?? 0),ratingsTotal:Number(r.ratings_total ?? 0),shortBio:r.short_bio,fullSummary:r.full_summary,pros:r.pros,cons:r.cons,reviews,sourceSufficient:r.source_sufficient===1,sourceVerified:r.source_verified===1,sourceProvider:r.source_provider||null,status:r.status,isExpired,expiredAt,purgeInSeconds,purgeInHours:purgeInSeconds===null?null:Number((purgeInSeconds/3600).toFixed(1)),priceCheckAt:r.price_check_at||null,rawSourceData:r.raw_source_data||null,created_date:r.created_at?new Date(r.created_at*1000).toISOString():null };
}

router.get('/stats',(req,res)=>{const deals=db.tables.deals||[],approved=deals.filter(d=>!d.is_expired&&d.status==='APPROVED'),pending=deals.filter(d=>d.status==='PENDING_REVIEW'),expired=deals.filter(d=>d.is_expired===1||d.status==='EXPIRED'),rejected=deals.filter(d=>d.status==='REJECTED');const lifecycle=db.getDealLifecycleStats();res.json({total:deals.length,approvedCount:approved.length,pendingCount:pending.length,expiredCount:expired.length,rejectedCount:rejected.length,readyToPurgeCount:lifecycle.readyToPurgeCount,avgDiscount:approved.length?Math.round(approved.reduce((a,d)=>a+Number(d.discount_percent||0),0)/approved.length):0,categoriesCount:(db.tables.categories||[]).length,bookmarksCount:(db.tables.bookmarks||[]).length,lifecycle});});

router.get('/:id/price-history',(req,res)=>{const deal=db.tables.deals.find(d=>d.id===req.params.id||d.asin===req.params.id);if(!deal)return res.status(404).json({error:'Deal not found'});res.json({history:db.getDealPriceHistory(deal),deal:rowToDeal(deal)});});

router.get('/',(req,res)=>{const {status,category,q,minDiscount,maxPrice,minPrice,minRating,sort='-created_date',limit=100}=req.query;let list=[...(db.tables.deals||[])];if(status)list=list.filter(d=>d.status===status);if(category&&category!=='All'&&category!=='All Deals')list=list.filter(d=>String(d.category||'').toLowerCase()===category.toLowerCase());if(q&&typeof q==='string'&&q.trim()){const term=q.trim().toLowerCase();list=list.filter(d=>[d.title,d.short_bio,d.full_summary,d.asin,d.category].some(v=>String(v||'').toLowerCase().includes(term)));}const n=(v)=>Number(v);if(Number.isFinite(n(minDiscount)))list=list.filter(d=>n(d.discount_percent)>=n(minDiscount));if(Number.isFinite(n(minPrice)))list=list.filter(d=>n(d.sale_price)>=n(minPrice));if(Number.isFinite(n(maxPrice)))list=list.filter(d=>n(d.sale_price)<=n(maxPrice));if(Number.isFinite(n(minRating)))list=list.filter(d=>n(d.rating)>=n(minRating));if(sort==='discount_desc'||sort==='-discount_percent')list.sort((a,b)=>n(b.discount_percent)-n(a.discount_percent));else if(sort==='price_asc')list.sort((a,b)=>n(a.sale_price)-n(b.sale_price));else if(sort==='price_desc')list.sort((a,b)=>n(b.sale_price)-n(a.sale_price));else if(sort==='rating_desc')list.sort((a,b)=>n(b.rating)-n(a.rating));else list.sort((a,b)=>n(b.created_at)-n(a.created_at));const safeLimit=Math.min(Math.max(Number.parseInt(limit,10)||100,1),100);res.json(list.slice(0,safeLimit).map(rowToDeal));});

const { ensureDealHasReviews }=require('../services/rainforestService');
router.get('/:id',async(req,res)=>{const row=db.tables.deals.find(x=>x.id===req.params.id||x.asin===req.params.id);if(!row)return res.status(404).json({error:'Deal not found'});if(row.source_verified){let reviews=[];try{reviews=typeof row.reviews==='string'?JSON.parse(row.reviews):(row.reviews||[]);}catch{}if(!reviews.length)try{await ensureDealHasReviews(row,db);}catch(err){console.warn('[reviews]',err.message);}}res.json(rowToDeal(row));});
router.post('/:id/sync-reviews',requireAdmin,async(req,res)=>{const row=db.tables.deals.find(x=>x.id===req.params.id||x.asin===req.params.id);if(!row)return res.status(404).json({error:'Deal not found'});if(!row.source_verified)return res.status(409).json({error:'Deal is not source-verified'});try{row.reviews='[]';const reviews=await ensureDealHasReviews(row,db);db.saveDb();res.json({success:true,dealId:row.id,asin:row.asin,reviews,count:reviews.length,deal:rowToDeal(row)});}catch(err){res.status(502).json({error:'Unable to synchronize reviews'});}});

function validatePrices(original,sale){original=Number(original);sale=Number(sale);if(!Number.isFinite(original)||!Number.isFinite(sale)||original<=0||sale<0||sale>original)throw new Error('Invalid price values');return{original,sale,discount:Number((((original-sale)/original)*100).toFixed(1))};}
function validStatus(s){return ['PENDING_REVIEW','APPROVED','REJECTED','EXPIRED'].includes(s);}
router.post('/',requireAdmin,(req,res)=>{try{const b=req.body||{},asin=String(b.asin||'').trim().toUpperCase();if(!/^[A-Z0-9]{10}$/.test(asin))throw new Error('Valid 10-character Amazon ASIN is required');if(!b.title)throw new Error('Title is required');const p=validatePrices(b.originalPrice,b.salePrice);const status=b.status||'PENDING_REVIEW';if(!validStatus(status))throw new Error('Invalid deal status');if(status==='APPROVED'&&b.sourceVerified!==true)throw new Error('Only source-verified deals can be approved');const d={id:asin,title:String(b.title).trim(),asin,category:String(b.category||'Electronics').trim(),original_price:p.original,sale_price:p.sale,discount_percent:p.discount,image_url:b.imageUrl||'',product_url:b.productUrl||`https://www.amazon.com/dp/${asin}`,rating:Number(b.rating)||0,ratings_total:Number(b.ratingsTotal)||0,short_bio:b.shortBio||'',full_summary:b.fullSummary||'',pros:Array.isArray(b.pros)?b.pros.join('\n'):(b.pros||''),cons:Array.isArray(b.cons)?b.cons.join('\n'):(b.cons||''),reviews:typeof b.reviews==='string'?b.reviews:JSON.stringify(b.reviews||[]),source_sufficient:b.sourceSufficient===true?1:0,source_verified:b.sourceVerified===true?1:0,source_provider:b.sourceProvider||null,status,raw_source_data:b.rawSourceData||'',created_at:Math.floor(Date.now()/1000)};const i=db.tables.deals.findIndex(x=>x.id===asin||x.asin===asin);if(i>=0)db.tables.deals[i]={...db.tables.deals[i],...d};else db.tables.deals.unshift(d);db.saveDb();res.status(i>=0?200:201).json(rowToDeal(d));}catch(err){res.status(400).json({error:err.message});}});

router.patch('/:id',requireAdmin,(req,res)=>{const d=db.tables.deals.find(x=>x.id===req.params.id||x.asin===req.params.id);if(!d)return res.status(404).json({error:'Deal not found'});const b=req.body||{};if(b.asin!==undefined){const asin=String(b.asin).trim().toUpperCase();if(!/^[A-Z0-9]{10}$/.test(asin))return res.status(400).json({error:'Invalid ASIN'});d.asin=asin;}if(b.title!==undefined)d.title=String(b.title).trim();if(b.category!==undefined)d.category=String(b.category).trim();if(b.originalPrice!==undefined||b.salePrice!==undefined){try{const p=validatePrices(b.originalPrice??d.original_price,b.salePrice??d.sale_price);d.original_price=p.original;d.sale_price=p.sale;d.discount_percent=p.discount;}catch(e){return res.status(400).json({error:e.message});}}if(b.imageUrl!==undefined)d.image_url=b.imageUrl;if(b.productUrl!==undefined)d.product_url=b.productUrl;if(b.rating!==undefined)d.rating=Number(b.rating);if(b.ratingsTotal!==undefined)d.ratings_total=Number(b.ratingsTotal);if(b.shortBio!==undefined)d.short_bio=b.shortBio;if(b.fullSummary!==undefined)d.full_summary=b.fullSummary;if(b.pros!==undefined)d.pros=Array.isArray(b.pros)?b.pros.join('\n'):b.pros;if(b.cons!==undefined)d.cons=Array.isArray(b.cons)?b.cons.join('\n'):b.cons;if(b.reviews!==undefined)d.reviews=typeof b.reviews==='string'?b.reviews:JSON.stringify(b.reviews);if(b.sourceSufficient!==undefined)d.source_sufficient=b.sourceSufficient?1:0;if(b.sourceVerified!==undefined)d.source_verified=b.sourceVerified?1:0;if(b.sourceProvider!==undefined)d.source_provider=b.sourceProvider;if(b.rawSourceData!==undefined)d.raw_source_data=b.rawSourceData;if(b.status!==undefined){if(!validStatus(b.status))return res.status(400).json({error:'Invalid deal status'});if(b.status==='APPROVED'&&d.source_verified!==1)return res.status(400).json({error:'Only source-verified deals can be approved'});d.status=b.status;}db.saveDb();res.json(rowToDeal(d));});

router.post('/approve-all',requireAdmin,(req,res)=>{let updatedCount=0;for(const d of db.tables.deals||[])if(d.status==='PENDING_REVIEW'&&d.source_verified===1){d.status='APPROVED';updatedCount++;}db.saveDb();res.json({success:true,approvedCount:updatedCount});});
router.post('/bulk-status',requireAdmin,(req,res)=>{const{ids=[],status='APPROVED'}=req.body||{};if(!Array.isArray(ids)||!validStatus(status))return res.status(400).json({error:'Invalid ids or status'});let updatedCount=0;for(const d of db.tables.deals||[])if(ids.includes(d.id)||ids.includes(d.asin)){if(status!=='APPROVED'||d.source_verified===1){d.status=status;updatedCount++;}}db.saveDb();res.json({success:true,updatedCount});});
router.post('/:id/expire',requireAdmin,(req,res)=>{const updated=db.expireDeal(req.params.id,(req.body||{}).reason||'Manually marked as expired by Admin');if(!updated)return res.status(404).json({error:'Deal not found'});res.json({success:true,deal:rowToDeal(updated)});});
router.post('/:id/restore',requireAdmin,(req,res)=>{const updated=db.restoreDeal(req.params.id);if(!updated)return res.status(404).json({error:'Deal not found'});res.json({success:true,deal:rowToDeal(updated)});});
router.post('/purge-expired',requireAdmin,(req,res)=>{const hours=Number((req.body||{}).maxAgeHours??24);if(!Number.isFinite(hours)||hours<0)return res.status(400).json({error:'Invalid maxAgeHours'});res.json({success:true,...db.purgeExpiredDeals(hours*3600)});});
router.delete('/:id',requireAdmin,(req,res)=>{const i=db.tables.deals.findIndex(x=>x.id===req.params.id||x.asin===req.params.id);if(i!==-1){db.tables.deals.splice(i,1);db.saveDb();}res.json({success:true});});
module.exports=router;